### ISSUE TITLE
Modernizr grunt broken?

### ISSUE THREAD

**Issue by GrimaceOfDespair** [Modernizr/grunt-modernizr#118]
It seems that Modernizr has a new release, which I think, breaks grunt-modernizr:

https://modernizr.com/news/modernizr-3-new-release-site

Currently, with 0.6.0, I'm getting the following:
```
Downloading source files
404 modernizr.load.1.5.4.js
404 modernizr-latest.js

>> Generating a custom Modernizr build
>> Uglifying
Writing assets/js/vendor/modernizr.min.js...OK

>> Wrote file to assets/js/vendor/modernizr.min.js
>> The following tests could not be downloaded
>>
>>     404 http://modernizr.com/i/js/modernizr.load.1.5.4.js
>>     404 http://modernizr.com/downloads/modernizr-latest.js
>>
>>     Check the Modulizr API for more info:
>>     https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157
```

**Comment by GrimaceOfDespair** [comment]
I think the solution would be to use a hosted version of the old modernizr.

Dug a bit into this: modernizr has been [deprecating Modernizr.Load](https://github.com/Modernizr/Modernizr/issues/1182) in favor of yepnope.js, who seem to have [deprecating themselves](https://github.com/SlexAxton/yepnope.js#deprecation-notice) :S

**Comment by SlexAxton** [comment]
For context, `Modernizr.load` *is*/always-was yepnope.js - but it's no longer considered a best practice. So it was deprecated a year or so ago both in Modernizr and out.

**Comment by SlexAxton** [comment]
But I don't think Modernizr.load is related to this issue.

**Comment by metaloha** [comment]
Building on @GrimaceOfDespair solution above, https://github.com/Modernizr/grunt-modernizr/pull/119. I consider it a temporary solution until the plugin is updated to work with v3.

**Comment by program247365** [comment]
I'm definitely seeing this too. Any ETA on when this will be fixed?

```
Running "modernizr:modernizr" (modernizr) task

Enabled Extras
>> cssclasses

Enabled Extensibility Options
>> prefixed
>> addtest

Downloading source files
404 modernizr-latest.js

Adding custom tests
>> assets/scripts/modernizr-custom/webkit-css-mask.js

>> Generating a custom Modernizr build
>> Uglifying

>> Wrote file to assets/lib/modernizr/modernizr-custom.js
>> The following tests could not be downloaded
>>
>>     404 http://modernizr.com/downloads/modernizr-latest.js
>>
>>     Check the Modulizr API for more info:
>>     https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157
```

**Comment by neilferreira** [comment]
+1

**Comment by SpoBo** [comment]
http://modernizr.com/downloads/modernizr-latest.js seems to be missing. Is this a hosting issue? Did the latest build break?

**Comment by Ben-Ho** [comment]
+1

**Comment by SlexAxton** [comment]
There is no longer such a thing as a Modernizr-latest.js file. There used to be a core Modernizr file we used on our site for development purposes (never as something people should be using). But since 3.0 that file no longer exists. It's built programmatically based on the tests you pass the builder.

That doesn't mean someone can't build a copy of Modernizr with every test turned on and host it at a URL, but we can't condone that for performance reasons.

**Comment by markusfalk** [comment]
Can't the grunt task just use the 'devFile' that is installed via bower?

**Comment by asha23** [comment]
I have found that the compile task is showing 404 errors also this morning...

This has forced us to go back to using locally sourced modernizr files... 

Any idea when the 404's will stop happening and we can get back to normal? Or will I need to exclude the grunt-modernizr task from everything - as currently it's rather borked for us. :D

![screenshot 2015-09-14 11 53 15](https://cloud.githubusercontent.com/assets/944262/9848250/39f0a6f2-5ad7-11e5-9ea2-02a804a51840.png)

**Comment by costasapostolopoulos** [comment]
+1

**Comment by dagstuan** [comment]
+1

**Comment by campsafari** [comment]
+1

**Comment by markusfalk** [comment]
Please stop notifying people with '+1' posts :-/

**Comment by thorsten** [comment]
@SlexAxton so Modernizr v3 broke grunt-modernizr?

**Comment by mrawdon** [comment]
Pointing http://modernizr.com/downloads/modernizr-latest.js to  http://modernizr.github.io/Modernizr/Modernizri/js/modernizr.load.1.5.4.js fixes this.  I still get a 404 on modernizr.load.1.5.4.js

**Comment by mzdr** [comment]
You can temporarily update your package.json to point to the fix from metaloha:

    "grunt-modernizr": "metaloha/grunt-modernizr#64aed149b36c23e9ecd987a47cd2ea212115baa4"

See the pull request: https://github.com/Modernizr/grunt-modernizr/pull/119

**Comment by metaloha** [comment]
I just updated the fork with an updated version number (thanks to https://github.com/dailymotion/grunt-modernizr/commit/a72cb3256286ed312b335579e9a33b67fdf29c59) - either don't attach the commit number to your `package.json` line (v2-fallback is the default branch), or use commit `59758451a623fd91314d4bbc0bce8533bd93db6e` instead.

**Comment by metaloha** [comment]
Updated again, now with v2.8.3 - `"grunt-modernizr": "metaloha/grunt-modernizr#d6657bf302bd9288e25a513197fb0e30c64ce677"`

**Comment by patricknelson** [comment]
Thanks @metaloha :+1: you're my personal hero :)  

Related issue (may want to open another new issue for this): It appears that this failure doesn't return a non-zero exit status. There were errors, but my capistrano deploy didn't fail like it should have in our UAT environment so everything was symlinked/launched as if everything was fine, but the end result was that we had broken JavaScript on the page (since Modernizr was never loaded).  

For example:

```
bash$ grunt compileJs

Downloading source files
404 modernizr.load.1.5.4.js
404 modernizr-latest.js

>> Generating a custom Modernizr build
>> Uglifying

>> Wrote file to themes/ebayinc/javascript/build/modernizr-custom.js
>> The following tests could not be downloaded
>>
>>     404 http://modernizr.com/i/js/modernizr.load.1.5.4.js
>>     404 http://modernizr.com/downloads/modernizr-latest.js
>>
>>     Check the Modulizr API for more info:
>>     https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157

Running "uglify:js" (uglify) task
>> 1 file created.

Done, without errors.
```

But, if you echo out the last exit status, it's still zero (and clearly there were errors):

```
bash$ echo $?
0
```

**Comment by thorsten** [comment]
Thanks @metaloha, your workaround is working nice.

**Comment by bramsmulders** [comment]
Thanks @metaloha, update is working great.
But this is a thing we'll need to fix in the future, mayb notify modernizr about a better api with legacy support. 
Because of now some very big projects have failing builds because of this.

Has anyone an idea on how fast this fix will be enabled in a release version of grunt-modernizr?
And mayb use modernizr v3 in future updates of grunt-modernizr?

**Comment by MartinJohns** [comment]
I think the biggest issue is that this error did not make the build fail - instead we got an basically empty Modernizr js file, which in return broke our website. A 404 on the JS download should make the grunt task fail.

**Comment by neilferreira** [comment]
I'm with @MartinJohns  and @patricknelson on this - The fact that you could deploy your site with capistrano (or w/e your build tool) and have the site still deploy just fine only to silently fail on live is not ideal.

**Comment by defualt** [comment]
I'm encountering the error with `404 modernizr-latest.js`.

I was puzzled because `/lib/cache/modernizr-latest.js` exists after a fresh `npm install`.  I eventually realized that the task sniffs this file's modified timestamp, and if the file is 7 days old it tries to fetch a later version.  To workaround this, I added the following to the top of my gruntfile.  Feels icky but gets the job done:

```
;(function(){
        var path = './node_modules/grunt-modernizr/lib/cache/modernizr-latest.js';
        var contents = grunt.file.read(path);
        grunt.file.write(path,contents);
})();
```

**Comment by mesfinbt** [comment]
This worked like a charm.  Thanks @defualt for the clever workaround!

**Comment by patricknelson** [comment]
**Side note:** For those of us who really *need* to be able to perform a fresh `npm install` (knowing the `node_modules` directory is going to be rebuilt), right now @metaloha's solution [above](https://github.com/Modernizr/grunt-modernizr/issues/118#issuecomment-140148638) is the best, since this means no `cache` directory would be present.

Now to @doctyper, would it make sense to possibly coordinate with @metaloha on setting up a pull request to fix this bug to have `grunt-modernizr` fail-over to the v2 build (possibly with a deprecation notice somewhere) but in the meantime get working on a newer version of this package that pulls in the newer version? I'm not sure what it'd entail to make the current package compatible with the newer version of of Modernizr, but at least people aren't manually monkey-patching their `package.json` (or their `Gruntfile.js`) just to get everything to work.

**Comment by doctyper** [comment]
@patrickkettner I don't know much about the 3.0 release. I've been out of Grunt / Modernizr land for a while now. I worked on a 3.0 port ages ago that might(?) still be compatible with the 3.0 release: https://github.com/Modernizr/grunt-modernizr/tree/feature/modernizr-3.0-standalone

I hope that helps. I think it's best for someone with a more current understanding of Grunt / Modernizr to take the reigns on this issue.

**Comment by patricknelson** [comment]
Did you mean @patricknelson? That's me :smile: 

But yeah -- that's essentially what I'm suggesting; half of it, at least. To go ahead with the merge requested in #119. Since you're the maintainer I think you'll need to merge+push the update. I know you made mention to "[merge away](https://github.com/Modernizr/grunt-modernizr/pull/119#issuecomment-140118540)" but I think only you have the access to do so to this repository, no? Who else can we tag to have this repo updated?

**Comment by doctyper** [comment]
This repo is owned by the Modernizr group. Anyone in the group should have push rights.

**Comment by metaloha** [comment]
Still waiting for someone in the Modernizr group to merge this. In the meantime, using `"grunt-modernizr": "metaloha/grunt-modernizr#v2-fallback"` in your package.json will give you a working version.

**Comment by ixisio** [comment]
+1 for merging #119.

\cc @SlexAxton @aFarkas @sindresorhus

**Comment by rmcveigh** [comment]
+1 for merge #119.

**Comment by Vinsanity** [comment]
+1 for merge #119 
Thanks for the fix @metaloha

**Comment by patrickkettner** [comment]
I created aliases for this at the nginx level for the new site. This will be around temporarily until the grunt plugin has been upgraded to support v3 for a few weeks.

Very sorry to anyone this has inconvenienced and/or royally screwed over.

**Comment by ixisio** [comment]
Thanks @patrickkettner for the quickfix :+1: 

The two links are working correctly now:

* http://modernizr.com/i/js/modernizr.load.1.5.4.js
* http://modernizr.com/downloads/modernizr-latest.js

**Comment by gunnx** [comment]
@patrickkettner 
Those links no longer working:(

**Comment by ixisio** [comment]
@gunnx Yep, I've also noticed today. Update `grunt-modernizr` package to v0.6.1 fixed it for me.

**Comment by patrickkettner** [comment]
Yep, they were removed intentionally. Please update to v1.0 or v0.6.1

**Comment by rupl** [comment]
Any way those URLs on modernizr.com could be set to 404 or maybe 410? I wrote downstream code which could handle a missing file but it currently returns 200 with empty body.

```
$ curl -i https://modernizr.com/downloads/modernizr-latest.js
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 17 Feb 2016 17:17:33 GMT
Content-Length: 0
Connection: keep-alive
cache-control: no-cache
Strict-Transport-Security: max-age=15768000

```

(the last line of this code block is the body, an empty string)

I'm updating my project to stop using these URLs, but there are ~11,000 drupal sites using the old code and I can't force an upgrade so the bug reports keep rolling in.

**Comment by patrickkettner** [comment]
@rupl done

**Comment by rupl** [comment]
@patrickkettner mucho appreciated!

**Comment by alandolsi** [comment]
can someone tell me how to fix that???

**Comment by patrickkettner** [comment]
@alandolsi fix what
