### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by johnsonlin** [Modernizr/grunt-modernizr#121]
https://modernizr.com/downloads/modernizr-latest.js
http://modernizr.com/i/js/modernizr.load.1.5.4.js

both return 404.

[modernizr](https://modernizr.com) recently updated their website.
API might have changed.

**Comment by SpikeShape** [comment]
Thats already a known issue:
see [issues #118](https://github.com/Modernizr/grunt-modernizr/issues/118)
There is a workaround for that which can be found [here](https://github.com/Modernizr/grunt-modernizr/issues/118#issuecomment-140148638)

As of now there doesn't seem to be an official merge so you might want to use that solution temporarily until the original grunt-modernizr gets a new release.

**Comment by bencevans** [comment]
:+1:

**Comment by patricknelson** [comment]
@johnsonlin @SpikeShape @bencevans 

FYI -- this has now been fixed in the aforementioned issue #118. I've haggled with one of the devs on a plan to move forward for those of us stuck with Modernizr v2, since this broke due to an update on the actual Modernizr site since they've now got new major version out (v3).

**Comment by bencevans** [comment]
Thanks for the update

**Comment by patrickkettner** [comment]
fixed by #118
