### ISSUE TITLE
v1.0.0 breaks functionality established of v0.6.x

### ISSUE THREAD

**Issue by bramsmulders** [Modernizr/grunt-modernizr#126]
Why is all the cool "parse files and only implement tests that the project needs" functionality remove from this project?

Currently its just a plain old modernizr builder. No automatic checking of css & js files whatsoever. Or am i missing something here?

**Comment by zenopopovici** [comment]
This update is moronic. Breaks all functionality. Don't understand what you people are thinking.

**Comment by SlexAxton** [comment]
+1. Agreed. This update has forsaken dignity.

Whoever has been responsible for this monstrosity is not only doomed to burn in hell, but I firmly and wholly wish that they live among hell on earth. At no point does this update even begin to constitute what anyone would consider a rational thought.

Go back to where we can build only the tests we need. Why would software be updated. The moral and spiritual inferiority that accompanies the decisions that I perceive that this project has made, regardless of the truth of those transgressions, lies firmly at the feet of the human slugs who flung this upon our grim species. You are moronic, terrible, awful people who deserve to be punished for this work that you force upon us.

May God have mercy on your souls.

**Comment by zenopopovici** [comment]
It seems that we can: https://github.com/doctyper/customizr#config-file but all configuration parameters have changed and have been replaced with other defaults THIS IS THE INSANITY.  In 7 days every configuration item has changed.

And of course nothing was documented in the changelog which still lists 0.6. I understand the need to release, but pushing such a release without saying it breaks all configuration, no documented changes ... this is not to be expected from the modernizr team.

**Comment by SlexAxton** [comment]
I say we find the team members and flog them publicly in shame.

**Comment by mashbodeploy** [comment]
I've been wasting a lot of time trying to get this all working again. I have it generating a file with only the tests I need. The problem is now that modernizr doesn't actually run. The development build works fine, but not the custom one based on what I need.

**Comment by evoactivity** [comment]
I've been wasting a lot of time trying to get this all working again. I have it generating a file with only the tests I need. The problem is now that modernizr doesn't actually run. The development build works fine, but not the custom one based on what I need.

**Comment by evoactivity** [comment]
Got it to run, apparently you now need to pass in options such as 'setClasses', that never used to be needed. The grunt config offered by the modernizr site wont actually work because all the configuration keys are different to what is actually required.

This is my grunt task now which is working

```modernizr: {
    dist: {
        devFile: false,
        dest: 'js/vendor/header/modernizr/modernizr.custom.js',
        files: {
            src: [
                'js/src/**/*.js',
                'styles/**/*.scss',
                'styles/**/*.css'
            ],
        },
        options: [
            'addTest',
            'testProp',
            'setClasses',
            'html5printshiv'
        ],
        matchCommunityTests: true,
        uglify: false
    }
}```

Wasted too much time getting this working again.

**Comment by zenopopovici** [comment]
@SlexAxton Whatever sarcasm you're using it's not working. It's a botched undocumented update that creates unnecessary frustration to Modernizr users. Scarcasm out of it how much as you want. Leave your pride aside and do what's needed. A little constructive feedback hasn't hurt anyone.

Here's a PR that addresses these issues. Furthermore --save-dev installs grunt-modernizr with ^ (so 0.6.0 were automatically updated to 1.0.0 thus breaking configs.

**Comment by bobthecow** [comment]
> A little constructive feedback hasn't hurt anyone.

[previously]

> This update is moronic.

You and I have different definitions of constructive feedback.

**Comment by SlexAxton** [comment]
There are very simple ways to work together to solve problems that arise in open source libraries. Those methods are used tons of times in this project every day. You exercised zero of those options. You aren't owed anything. I'm sorry that a *major version bump* broke backwards compatibility, but it was a... major version bump.

In the case of grunt-modernizr, it was very recently given over to the Modernizr team from a community member. It's not something we've maintained in the past, and it's something we're figuring out how to maintain in the future (if at all), especially since the Modernizr project now does many of the things that grunt-modernizr used to do. Not to mention that all versions of Modernizr in npm and bower were unofficial.

> Whatever sarcasm you're using it's not working.

Let me tell you about what's not working.

If you'd like to see this project move forward then feel free to contribute to it nicely, but I'd skip over a good pull request with a shitty message a thousand times.

**How you talk to people matters.**

If you're a jerk on the internet, *you're a jerk in real life.*

**Comment by zenopopovici** [comment]
Would you be so kind to stop throwing insults around and make it personal. It's really not. I have not insulted anyone here, so please do me the same curtesy.

You botched a release ... it's also normal for people to get frustrated if their projects are automatically updated  and get broken. Did I mention that grunt-modernizr installs with a "^" in package.json and not with a "~" ?. People are not machines you know and they do get upset. 

It's irresponsible do a release in this way (no clear readme, no updated changelog, no references to an update that breaks configs/functionality) no matter if the project is open source or not.  This is a software that is used by thousands of people and that should attract some responsible standardized way to manage the repository and releases.

Now about that "shitty message": I was merely copying a really cool guy (https://github.com/jkphl/grunt-svg-sprite). You might know him. He wrote a few books on JS. I think his readme files and changelogs are quite informative and cannot be qualified as "shitty". I do hope you reconsider the PR, or at least make the changes yourself with what you consider "non-shitty".

Now, if I offended you in any way I do apologize. I'm not a native speaker and as I mentioned people get upset. But I never called anyone a "jerk" or qualified their work as "shitty". The only thing I said was that the update was moronic. Because I really believed it was. If you go trough the readme, the link is at the very bottom and from the first glance you only notice the empty config.

**Comment by ljharb** [comment]
(neither `^0.6.0` nor `~0.6.0` automatically updates to `v1.0.0` - you can check this on http://semver.npmjs.com/)

**Comment by zenopopovici** [comment]
@ljharb I was under the impression ^ did update major versions. Don't really understand how my project got updated... I'll investigate. Thanks for the clarification.

**Comment by seavor** [comment]
`I'm sorry that a major version bump broke backwards compatibility, but it was a... major version bump.`

That would be all well and good @SlexAxton, if 0.6.0 wasn't broken in the process. The links to Modernizr HQ that 0.6.0 depends on no longer even exist:

http://modernizr.com/i/js/modernizr.load.1.5.4.js
http://modernizr.com/downloads/modernizr-latest.js

It's one thing for a major version bump to not be backwards compatible, quite another for a MVB to completely break legacy versions of the code that may still be in use. This was a botched operation, whoever headed it up, and deserves some kind of acknowledgement and response from Modernizr team to the countless devs and projects that depend on the software. Not some p/c response that essentially amounted to a "f$%k off, you don't know me" dismissal.
